application: worker-converter
version: 1
runtime: python310 # or another supported version
threadsafe: true

instance_class: F2

env_variables:
  BUCKET_NAME: "audio_storage_cloud"

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: app.py